In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [18]:
data=pd.read_csv("HR.csv")
data.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low

In [19]:
data.columns

Index(['satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident', 'left',
       'promotion_last_5years', 'sales', 'salary'],
      dtype='object')

In [20]:
data.shape

(14999, 10)

In [21]:
data.dtypes

satisfaction_level       float64
last_evaluation          float64
number_project             int64
average_montly_hours       int64
time_spend_company         int64
Work_accident              int64
left                       int64
promotion_last_5years      int64
sales                     object
salary                    object
dtype: object

In [22]:
data.isnull().sum()

satisfaction_level       0
last_evaluation          0
number_project           0
average_montly_hours     0
time_spend_company       0
Work_accident            0
left                     0
promotion_last_5years    0
sales                    0
salary                   0
dtype: int64

In [23]:
data[data.duplicated()]

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
396,0.46,0.57,2,139,3,0,1,0,sales,low
866,0.41,0.46,2,128,3,0,1,0,accounting,low
1317,0.37,0.51,2,127,3,0,1,0,sales,medium
1368,0.41,0.52,2,132,3,0,1,0,RandD,low
1461,0.42,0.53,2,142,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...,...
14994,0.40,0.57,2,151,3,0,1,0,support,low
14995,0.37,0.48,2,160,3,0,1,0,support,low
14996,0.37,0.53,2,143,3,0,1,0,support,low
14997,0.11,0.96,6,280,4,0,1,0,support,low
14998,0.37,0.52,2,158,3,0,1,0,support,low

In [24]:
data.drop_duplicates(inplace=True,ignore_index=True)

In [25]:
data.shape

(11991, 10)

In [26]:
# sales is an object column

data["sales"].nunique()

10

In [27]:
data = pd.get_dummies(data)

In [28]:
data.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales_IT,sales_RandD,...,sales_hr,sales_management,sales_marketing,sales_product_mng,sales_sales,sales_support,sales_technical,salary_high,salary_low,salary_medium
0,0.38,0.53,2,157,3,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0
1,0.80,0.86,5,262,6,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,1
2,0.11,0.88,7,272,4,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,1
3,0.72,0.87,5,223,5,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0
4,0.37,0.52,2,159,3,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [29]:
data.corr()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales_IT,sales_RandD,...,sales_hr,sales_management,sales_marketing,sales_product_mng,sales_sales,sales_support,sales_technical,salary_high,salary_low,salary_medium
satisfaction_level,1.000000,0.095186,-0.133246,-0.006252,-0.152915,0.039940,-0.350558,0.019789,0.005382,-0.002552,...,-0.007348,0.001883,0.005171,0.000171,0.004268,0.009064,-0.003426,0.017031,-0.027838,0.018579
last_evaluation,0.095186,1.000000,0.270256,0.264678,0.096829,-0.005695,0.013520,-0.007206,-0.002885,-0.005448,...,-0.001354,0.011106,0.002546,-0.004233,-0.022711,0.015876,0.008859,-0.017543,0.010416,-0.000755
number_project,-0.133246,0.270256,1.000000,0.331516,0.188837,-0.005612,0.030928,-0.000544,-0.001464,0.010077,...,-0.025142,0.005729,-0.017232,-0.001777,-0.013473,0.006594,0.023235,-0.002820,-0.000914,0.002484
average_montly_hours,-0.006252,0.264678,0.331516,1.000000,0.102875,-0.012860,0.070409,-0.004964,0.001007,0.004159,...,-0.005197,0.004211,-0.004935,-0.007987,-0.002890,0.001334,0.006321,-0.002499,-0.000675,0.002065
time_spend_company,-0.152915,0.096829,0.188837,0.102875,1.000000,0.000003,0.173295,0.056828,-0.003233,-0.008380,...,-0.018757,0.090071,0.010474,-0.004398,0.007233,-0.022955,-0.020051,0.029111,-0.032541,0.016612
Work_accident,0.039940,-0.005695,-0.005612,-0.012860,0.000003,1.000000,-0.125436,0.029852,-0.009777,0.011793,...,-0.013463,0.005837,0.004181,0.003144,-0.000895,0.011613,-0.004268,0.002735,0.001580,-0.003108
left,-0.350558,0.013520,0.030928,0.070409,0.173295,-0.125436,1.000000,-0.044657,-0.003324,-0.029016,...,0.013567,-0.024417,0.000248,-0.003768,0.006154,0.006019,0.010000,-0.094769,0.099113,-0.047214
promotion_last_5years,0.019789,-0.007206,-0.000544,-0.004964,0.056828,0.029852,-0.044657,1.000000,-0.034334,0.025610,...,0.002446,0.098835,0.043833,-0.032326,0.004609,-0.026709,-0.026502,0.063982,-0.076576,0.041601
sales_IT,0.005382,-0.002885,-0.001464,0.001007,-0.003233,-0.009777,-0.003324,-0.034334,1.000000,-0.073779,...,-0.068377,-0.057822,-0.072586,-0.073326,-0.181086,-0.125958,-0.142826,-0.010617,0.005370,0.000482
sales_RandD,-0.002552,-0.005448,0.010077,0.004159,-0.008380,0.011793,-0.029016,0.025610,-0.073779,1.000000,...,-0.056934,-0.048146,-0.060439,-0.061056,-0.150782,-0.104880,-0.118925,-0.013363,-0.007301,0.014761
sales_accounting,-0.021056,0.007244,0.006286,0.001938,0.006910,-0.009178,0.005955,-0.001497,-0.069566,-0.057925,...,-0.053684,-0.045397,-0.056989,-0.057569,-0.142173,-0.098892,-0.112135,0.016038,-0.000955,-0.007934
sales_hr,-0.007348,-0.001354,-0.025142,-0.005197,-0.018757,-0.013463,0.013567,0.002446,-0.068377,-0.056934,...,1.000000,-0.044620,-0.056014,-0.056585,-0.139742,-0.097201,-0.110218,-0.016137,0.006355,0.002552
sales_management,0.001883,0.011106,0.005729,0.004211,0.090071,0.005837,-0.024417,0.098835,-0.057822,-0.048146,...,-0.044620,1.000000,-0.047368,-0.047850,-0.118171,-0.082196,-0.093204,0.148935,-0.062171,-0.020015
sales_marketing,0.005171,0.002546,-0.017232,-0.004935,0.010474,0.004181,0.000248,0.043833,-0.072586,-0.060439,...,-0.056014,-0.047368,1.000000,-0.060069,-0.148346,-0.103185,-0.117003,0.008473,-0.008820,0.004180
sales_product_mng,0.000171,-0.004233,-0.001777,-0.007987,-0.004398,0.003144,-0.003768,-0.032326,-0.073326,-0.061056,...,-0.056585,-0.047850,-0.060069,1.000000,-0.149858,-0.104237,-0.118196,-0.006051,0.010507,-0.007222
sales_sales,0.004268,-0.022711,-0.013473,-0.002890,0.007233,-0.000895,0.006154,0.004609,-0.181086,-0.150782,...,-0.139742,-0.118171,-0.148346,-0.149858,1.000000,-0.257422,-0.291896,-0.020758,0.000946,0.010561
sales_support,0.009064,0.015876,0.006594,0.001334,-0.022955,0.011613,0.006019,-0.026709,-0.125958,-0.104880,...,-0.097201,-0.082196,-0.103185,-0.104237,-0.257422,1.000000,-0.203035,-0.020555,-0.002186,0.013601
sales_technical,-0.003426,0.008859,0.023235,0.006321,-0.020051,-0.004268,0.010000,-0.026502,-0.142826,-0.118925,...,-0.110218,-0.093204,-0.117003,-0.118196,-0.291896,-0.203035,1.000000,-0.014970,0.027315,-0.019194
salary_high,0.017031,-0.017543,-0.002820,-0.002499,0.029111,0.002735,-0.094769,0.063982,-0.010617,-0.013363,...,-0.016137,0.148935,0.008473,-0.006051,-0.020758,-0.020555,-0.014970,1.000000,-0.287464,-0.265233
salary_low,-0.027838,0.010416,-0.000914,-0.000675,-0.032541,0.001580,0.099113,-0.076576,0.005370,-0.007301,...,0.006355,-0.062171,-0.008820,0.010507,0.000946,-0.002186,0.027315,-0.287464,1.000000,-0.847243
salary_medium,0.018579,-0.000755,0.002484,0.002065,0.016612,-0.003108,-0.047214,0.041601,0.000482,0.014761,...,0.002552,-0.020015,0.004180,-0.007222,0.010561,0.013601,-0.019194,-0.265233,-0.847243,1.000000

In [30]:
X = data.drop(["left"],axis=1).values   #values mathram edukkunnath numpy array aakan because speed kudan
y=data["left"].values

In [31]:
sc = StandardScaler()
X = sc.fit_transform(X)

In [32]:
X

array([[-1.03566801, -1.10899046, -1.54992118, ..., -0.29998636,
         1.04356331, -0.88415136],
       [ 0.70663718,  0.85137984,  1.02919412, ..., -0.29998636,
        -0.95825523,  1.13102806],
       [-2.15572134,  0.97019016,  2.74860432, ..., -0.29998636,
        -0.95825523,  1.13102806],
       ...,
       [ 0.91405447, -1.0495853 , -0.69021608, ...,  3.33348485,
        -0.95825523, -0.88415136],
       [-1.24308529, -0.39612853, -0.69021608, ...,  3.33348485,
        -0.95825523, -0.88415136],
       [-0.53786652,  0.07911275,  0.16948902, ..., -0.29998636,
         1.04356331, -0.88415136]])

In [33]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

pca =PCA(n_components=2)
X_pca = pca.fit_transform(X)  


print("The original shape :",X.shape)
print("The new PCA shape :",X_pca.shape)
X_train,X_test,y_train,y_test = train_test_split(X_pca,y,test_size=0.3,random_state=10)

ss = SVC()
ss.fit(X_train,y_train)

print("Train score :",ss.score(X_train,y_train))
print("Test score :",ss.score(X_test,y_test))

The original shape : (11991, 20)
The new PCA shape : (11991, 2)
Train score : 0.9098057905397355
Test score : 0.9141189549749861

In [34]:
# pca=3

pca =PCA(n_components=3)
X_pca = pca.fit_transform(X)  


print("The original shape :",X.shape)
print("The new PCA shape :",X_pca.shape)
X_train,X_test,y_train,y_test = train_test_split(X_pca,y,test_size=0.3,random_state=10)

ss = SVC()
ss.fit(X_train,y_train)

print("Train score :",ss.score(X_train,y_train))
print("Test score :",ss.score(X_test,y_test))

The original shape : (11991, 20)
The new PCA shape : (11991, 3)
Train score : 0.9150482544977958
Test score : 0.914396887159533

In [35]:
# pca =6

pca =PCA(n_components=6)
X_pca = pca.fit_transform(X)  


print("The original shape :",X.shape)
print("The new PCA shape :",X_pca.shape)
X_train,X_test,y_train,y_test = train_test_split(X_pca,y,test_size=0.3,random_state=10)

ss = SVC()
ss.fit(X_train,y_train)

print("Train score :",ss.score(X_train,y_train))
print("Test score :",ss.score(X_test,y_test))

The original shape : (11991, 20)
The new PCA shape : (11991, 6)
Train score : 0.9372095794114143
Test score : 0.9385769872151195

In [36]:
#pca =18

pca =PCA(n_components=18)
X_pca = pca.fit_transform(X)  


print("The original shape :",X.shape)
print("The new PCA shape :",X_pca.shape)
X_train,X_test,y_train,y_test = train_test_split(X_pca,y,test_size=0.3,random_state=10)

ss = SVC()
ss.fit(X_train,y_train)

print("Train score :",ss.score(X_train,y_train))
print("Test score :",ss.score(X_test,y_test))

The original shape : (11991, 20)
The new PCA shape : (11991, 18)
Train score : 0.95794114142738
Test score : 0.9571984435797666

In [37]:
# random forest

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

pca =PCA(n_components=20)
X_pca = pca.fit_transform(X)  


print("The original shape :",X.shape)
print("The new PCA shape :",X_pca.shape)
X_train,X_test,y_train,y_test = train_test_split(X_pca,y,test_size=0.3,random_state=10)

ss = RandomForestClassifier()
ss.fit(X_train,y_train)

print("Train score :",ss.score(X_train,y_train))
print("Test score :",ss.score(X_test,y_test))

The original shape : (11991, 20)
The new PCA shape : (11991, 20)
Train score : 1.0
Test score : 0.971372984991662

In [38]:
# pca =5

pca =PCA(n_components=5)
X_pca = pca.fit_transform(X)  


print("The original shape :",X.shape)
print("The new PCA shape :",X_pca.shape)
X_train,X_test,y_train,y_test = train_test_split(X_pca,y,test_size=0.3,random_state=10)

ss = RandomForestClassifier()
ss.fit(X_train,y_train)

print("Train score :",ss.score(X_train,y_train))
print("Test score :",ss.score(X_test,y_test))

The original shape : (11991, 20)
The new PCA shape : (11991, 5)
Train score : 1.0
Test score : 0.9549749861033908

In [39]:
pca =PCA(n_components=2)
X_pca = pca.fit_transform(X)  


print("The original shape :",X.shape)
print("The new PCA shape :",X_pca.shape)
X_train,X_test,y_train,y_test = train_test_split(X_pca,y,test_size=0.3,random_state=10)

ss = RandomForestClassifier()
ss.fit(X_train,y_train)

print("Train score :",ss.score(X_train,y_train))
print("Test score :",ss.score(X_test,y_test))

The original shape : (11991, 20)
The new PCA shape : (11991, 2)
Train score : 1.0
Test score : 0.9313507504168983